### ISSUE TITLE
[Enhancement] - Create an icon for the website

### ISSUE THREAD

**Issue by VivekChatterjee** [VivekChatterjee/Tour-Website#2]
Create an icon for the website matching its purpose

**Comment by DarkSoul26** [comment]
@VivekChatterjee let me take a look into this

**Comment by VivekChatterjee** [comment]
Sure @DarkSoul26 go ahead

**Comment by DarkSoul26** [comment]
Icon means logo right @VivekChatterjee

**Comment by VivekChatterjee** [comment]
Yes the logo and the favicon (the icon which shows beside the url on tab)

**Comment by DarkSoul26** [comment]
On the navbar right

**Comment by VivekChatterjee** [comment]
@DarkSoul26 just change this icon:

![image](https://github.com/VivekChatterjee/Tour-Website/assets/77501726/9611d122-de4a-4bb0-b206-913747edef4c)

**Comment by gautamb02** [comment]
Heyy,

assign this to me !!

**Comment by DarkSoul26** [comment]
Thanks
