### ISSUE TITLE
[FIX] - In dark mode, black part in the logo is not visible

### ISSUE THREAD

**Issue by VivekChatterjee** [VivekChatterjee/Tour-Website#3]
I am currently using a favicon for the project so In dark mode the black part is not visible.
Maybe have to use a different icon in dark mode.

**Comment by pt21v** [comment]
Hi @VivekChatterjee , assign to me, please!

**Comment by VivekChatterjee** [comment]
@ivanetra go ahead.

**Comment by pt21v** [comment]
Thanks, @VivekChatterjee !
